# Generated by Django 5.1.6 on 2025-02-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
