# Generated by Django 5.1.6 on 2025-02-15 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0002_bookmodel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='author',
        ),
    ]
