# Generated by Django 5.1.6 on 2025-02-15 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0005_alter_bookmodel_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='author',
        ),
    ]
